"""another migration

Revision ID: 122d04e5998f
Revises: 75399d16e790
Create Date: 2020-12-04 06:06:09.058258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '122d04e5998f'
down_revision = '75399d16e790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_number', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone_number')
    # ### end Alembic commands ###
